services:
  backend:
    image: studypal-backend:ci
    environment:
      - PORT=8080                 # app listens on 8080 in the container
      - DB_PATH=/app/study_pal.db # same file every time
    ports:
      - "8000:8000"               # host:container
    volumes:
      - ./Backend/study_pal.db:/app/study_pal.db  # file persists on host

  frontend:
    image: studypal-frontend:ci
    depends_on:
      - backend
    ports:
      - "3000:80"
