services:
  backend:
    image: studypal-backend:ci
    environment:
      - PORT=8080
    ports:
      - "8000:8080"  # host:container

  frontend:
    image: studypal-frontend:ci
    depends_on:
      - backend
    ports:
      - "3000:80"
