services:
  backend:
    image: studypal-backend:ci
    environment:
      PORT: "8000"
      DB_PATH: /app/data/study_pal.db
    ports:
      - "8000:8000"
    volumes:
      - studypal_db:/app/data
    # optional: rely on container's own HEALTHCHECK and wait before tests
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/health >/dev/null || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 2s

volumes:
  studypal_db:
