services:
  backend:
    image: studypal-backend:ci
    environment:
      - PORT=8000
      - DB_PATH=/app/data/study_pal.db
    ports:
      - "8000:8000"
    volumes:
      - studypal_db:/app/data

volumes:
  studypal_db:
